name: Build and Publish

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm install
      - name: compile typescript
        run: npm run build
      - name: npm publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
